### ISSUE TITLE
Unable to compile client at HEAD

### ISSUE THREAD

**Issue by skuruppu** [googleapis/nodejs-spanner#1209]
I was attempting to run unit and integration tests with npm and started getting this issue.

#### Environment details

  - OS: Debian
  - Node.js version: v10.21.0
  - npm version: 6.14.6
  - `@google-cloud/spanner` version: HEAD at 6e1f300ebe31027eb1f2922facb70bb0ba392b11 (5.2.1)

#### Steps to reproduce

  1. npm install
  2. npm run system-test

```
TypeError: Cannot read property 'Reader' of undefined
    at <path>/nodejs-spanner/build/protos/protos.js:28:29
    at <path>/nodejs-spanner/build/protos/protos.js:22:26
    at Object.<anonymous> (<path>/nodejs-spanner/build/protos/protos.js:24:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<path>/nodejs-spanner/build/src/codec.js:22:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<path>/nodejs-spanner/build/src/index.js:27:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<path>/nodejs-spanner/build/system-test/spanner.js:27:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.exports.requireOrImport (<path>/nodejs-spanner/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (<path>/nodejs-spanner/node_modules/mocha/lib/esm-utils.js:33:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by skuruppu** [comment]
Note that this seems to just be an issue that I have in my environment. Haven't yet found anyone else that can reproduce this.

**Comment by olavloite** [comment]
@skuruppu I had this same problem the other day. The solution in my case was to manually delete the `build` and `node_modules` directories in my project directory, and then run `npm install`. After that it was gone.

**Comment by skuruppu** [comment]
Oh no, I tried to do this with `node_modules` before and it didn't work. Now I tried both by deleting `build` and `node_modules`. Still no luck :(

**Comment by skuruppu** [comment]
Also remove `~/.npm` and `~/npm-global`. Still no luck.

Weirdly, I was able to freshly install npm on a new machine and get it working. Just doesn't work on my normal machine.

**Comment by stephenplusplus** [comment]
Something is going on: https://github.com/googleapis/nodejs-pubsub/issues/1082#issuecomment-671120918

**Comment by hengfengli** [comment]
A possible solution: https://github.com/googleapis/nodejs-pubsub/issues/1082#issuecomment-671630706.

**Comment by skuruppu** [comment]
Very interesting, https://github.com/googleapis/nodejs-pubsub/issues/1082#issuecomment-671630706 did work indeed.

Maybe I'll make the same change as https://github.com/googleapis/nodejs-pubsub/pull/1085 here.
