### ISSUE TITLE
Large Query Request sometimes results in TypeError: value.map is not a function

### ISSUE THREAD

**Issue by jsjaspreet** [googleapis/nodejs-spanner#153]
#### Environment details

  - OS: Ubuntu 16.04 LTS
  - Node.js version: v8.9.3
  - npm version: 5.7.1
  - @google-cloud/spanner version: 1.1.0

#### Steps to reproduce

  1. Have a table ready with thousands of rows
  2. Use the Spanner client library's `database.run` function to run a query like below where the limit is high (I'm seeing limit fail at 1000):

```
SELECT * FROM someTable WHERE x > 0
ORDER BY id LIMIT @someLimit OFFSET @someOffset'
```
  3.  This intermittent error sometimes pops up.

```
/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/@google-cloud/spanner/src/row-builder.js:67
    return value.map(function(value) {
                 ^
TypeError: value.map is not a function
    at Function.RowBuilder.formatValue (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/@google-cloud/spanner/src/row-builder.js:67:18)
    at /home/jsjaspreet/dev/honey/internal-api-stores/node_modules/@google-cloud/spanner/src/row-builder.js:171:27
    at Array.forEach (<anonymous>:null:null)
    at /home/jsjaspreet/dev/honey/internal-api-stores/node_modules/@google-cloud/spanner/src/row-builder.js:166:12
    at Array.map (<anonymous>:null:null)
    at RowBuilder.toJSON (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/@google-cloud/spanner/src/row-builder.js:162:20)
    at DestroyableTransform._transform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/@google-cloud/spanner/src/partial-result-stream.js:103:52)
    at DestroyableTransform.Transform._read (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at DestroyableTransform.obj.(anonymous function) [as _write] (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/stubs/index.js:26:26)
    at doWrite (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.ondata (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at Pumpify.emit (events.js:211:7)
    at Pumpify.emit (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/events-intercept/lib/events-intercept.js:70:26)
    at addChunk (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Pumpify.Readable.push (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at /home/jsjaspreet/dev/honey/internal-api-stores/node_modules/split-array-stream/index.js:15:14
    at Object.whilst (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/async/dist/async.js:5213:5)
    at module.exports (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/split-array-stream/index.js:9:9)
    at Pumpify.combinedStream.flush (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/checkpoint-stream/index.js:69:5)
    at DestroyableTransform._transform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/checkpoint-stream/index.js:45:20)
    at DestroyableTransform.Transform._read (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/duplexify/index.js:201:22)
    at doWrite (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Pumpify.Writable.write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at PassThrough.ondata (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at PassThrough.emit (events.js:211:7)
    at PassThrough.emit (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/events-intercept/lib/events-intercept.js:70:26)
    at addChunk (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at PassThrough.Readable.push (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at PassThrough.Transform.push (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at afterTransform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:102:51)
    at TransformState.afterTransform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at PassThrough._transform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_passthrough.js:46:3)
    at PassThrough.Transform._read (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at PassThrough.Transform._write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at PassThrough.Writable.write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at DestroyableTransform.ondata (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at addChunk (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at DestroyableTransform.Readable.push (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at DestroyableTransform.Transform.push (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at afterTransform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:102:51)
    at TransformState.afterTransform (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at DestroyableTransform.obj.(anonymous function) [as _write] (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/stubs/index.js:26:26)
    at doWrite (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at StreamProxy.ondata (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:116:13)
    at StreamProxy.emit (events.js:211:7)
    at ClientReadableStream.<anonymous> (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/google-gax/lib/streaming.js:152:17)
    at emitOne (events.js:116:13)
    at ClientReadableStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientReadableStream.Readable.push (_stream_readable.js:208:10)
    at readCallback (/home/jsjaspreet/dev/honey/internal-api-stores/node_modules/grpc/src/client.js:299:14)
``` 

I'm able to get around this issue by lowering my page size to 500, and I looked around the documentation / other open issues to see if anyone ran into something similar but not seeing anyone report this so far. If you require more information, please let me know!

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce yet, using a table with 10,000+ rows and a limit of anywhere from 50 to 7500. Would you be able to prepare code that could reproduce an error, then I'll adapt to my database and table?

**Comment by jsjaspreet** [comment]
sure, let me write some reproducible code, will get back to you, thanks for the quick response!

**Comment by stephenplusplus** [comment]
@jsjaspreet any updates? :)

**Comment by jsjaspreet** [comment]
Sorry just got back from vacation, let me see if I still run into this
issue with the latest spanner version, will get back to you today!

**Comment by stephenplusplus** [comment]
No problem, take your time. Hope you had a good vacation!

**Comment by jsjaspreet** [comment]
Hey Stephen! Just want you to know I haven't forgotten this, still getting some reproducible code ready, will get to you soon.

**Comment by stephenplusplus** [comment]
@jsjaspreet I'm going to close, but I will re-open if you provide the reproduction code :)

**Comment by walshie4** [comment]
Just wanted to note we're still seeing this.  When we have some more free time we'll work on getting a repro repo setup.
