### ISSUE TITLE
4 DEADLINE_EXCEEDED: Deadline exceeded on update query

### ISSUE THREAD

**Issue by aayush-sib** [googleapis/nodejs-spanner#1589]
Hi, 
We are trying to update some records in one table, while performing this action sometimes we get this error
```
4 DEADLINE_EXCEEDED: Deadline exceeded
    at Object.callErrorFromStatus (/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at /node_modules/@grpc/grpc-js/build/src/call-stream.js:111:35
    at Object.onReceiveStatus (/node_modules/grpc-gcp/build/src/index.js:73:29)
    at InterceptingListenerImpl.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/call-stream.js:106:23)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  code: 4,
  details: 'Deadline exceeded',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

We are using this function to perform the update operation
```
await this.database.runPartitionedUpdate({
                ...options,
                gaxOptions: this.retryAndTimeoutSettings,
});
```

**Comment by asthamohta** [comment]
Hi @aayush-sib. runPartitionedUpdate are usually used for large updates. Can you share what your query is and how many rows are approximately getting updated along with your timeout settings. It is possible that it's simply getting timed out as it is a large operation and increasing the value for timeout should resolve it

**Comment by aayush-sib** [comment]
Hi @asthamohta 
Thanks for the reply, we are just updating one row. Can you share the function which we can use instead of this?

**Comment by asthamohta** [comment]
Assuming that you are running a query, this sample should help: https://github.com/googleapis/nodejs-spanner/blob/main/samples/dml.js

**Comment by aayush-sib** [comment]
We have tried with `runUpdate` function also, and the same intermittent issue was there with this function also.

**Comment by asthamohta** [comment]
Can you share your query and environments details which might help replicate the issue?

**Comment by asthamohta** [comment]
@aayush-sib just want to get back to you if this is still an open issue or something I can help with?

**Comment by asthamohta** [comment]
Closing this issue due to lack of activity, feel free to reopen this if you face the same issue
