### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined at SessionPool.getSessionGroup_ 

### ISSUE THREAD

**Issue by manasi99** [googleapis/nodejs-spanner#173]
I have a cloud function deployed on GCP which is triggered by Cloud Pub/Sub topic. It connects to cloud spanner to insert the pub/sub event data. It is a high volume pub/sub topic and make simultaneous insert requests in different cloud spanner table. However, it keep giving below errors intermittently. 

ERROR: 
TypeError: Cannot read property 'type' of undefined at SessionPool.getSessionGroup_ (/user_code/node_modules/@google-cloud/spanner/src/session-pool.js:709:17) at SessionPool.spliceSession_ (/user_code/node_modules/@google-cloud/spanner/src/session-pool.js:865:20) at SessionPool.borrowSession_ (/user_code/node_modules/@google-cloud/spanner/src/session-pool.js:419:8) at SessionPool.getNextAvailableSession_ (/user_code/node_modules/@google-cloud/spanner/src/session-pool.js:648:8) at /user_code/node_modules/@google-cloud/spanner/src/session-pool.js:936:19

Below are the dependencies in package.json
```
{
        "dependencies": {
                "safe-buffer": "5.1.1",
                "@google-cloud/spanner": "1.3.0",
                "google-gax": "^0.14.5"
        }
}
```

Thanks for your help.

**Comment by manasi99** [comment]
Sample Code for reference - 

```
const Spanner = require('@google-cloud/spanner');
const config = require('./config.js');

const spannerClient = new Spanner({
	projectId: config.PROJECT_ID
});

const spannerInstance = spannerClient.instance(config.INSTANCE_ID);

const spannerDatabase = spannerInstance.database(config.DATABASE_ID);

exports.upsertRows = function(tableName, rows) {
return new Promise((resolve, reject) => {
	try {
		const spannerTable = spannerDatabase.table(tableName);
		spannerTable.upsert(rows)
			.then(() => {
				console.log('Upserted data.');
				resolve(true);
			})
			.catch(err => {
				console.error(`Upsert `, err);
				reject(err);
			});
		});
	} catch (err) {
		console.error(`upsertRows `, err);
		reject(err);
	}
};

```

**Comment by callmehiphop** [comment]
@manasi99 thanks for reporting! I'm having a difficult time reproducing, but I think I have pinpointed the cause. I've opened a pr (https://github.com/googleapis/nodejs-spanner/pull/174) that I think will resolve it. Do you have any bandwidth to test the changes and confirm if the issue still exists?

**Comment by manasi99** [comment]
@callmehiphop I can test the changes. Can you tell me the version of cloud spanner I should use to test ?

**Comment by callmehiphop** [comment]
@manasi99 I haven't cut a release with this change, but you can install it with the following command

```sh
$ npm install callmehiphop/nodejs-spanner#dg--173 --save
```

**Comment by manasi99** [comment]
@callmehiphop : Can you please tell me after I install this fix, how should I deploy the cloud function with this version of nodejs-spanner ?

**Comment by stephenplusplus** [comment]
If you're comfortable testing a deploy with the pre-release branch @callmehiphop mentioned, it should be automatic. As long as you include the `--save` in your `npm install` command, it will be written to package.json, and that will be deployed and used.

**Comment by manasi99** [comment]
@callmehiphop We have pushed this fix in our testing environment and will monitor the cloud functions for a few days as it is an intermittent issue. I'll update you soon.

**Comment by manasi99** [comment]
@callmehiphop  Thanks for your patience Dave. We are good to go with this fix as we have not seen this error occurring in our test environment.

**Comment by Chipintoza** [comment]
@callmehiphop - Hello
i have same issue

```
InternalServerError: err.code: undefined
err.message: Cannot read property 'type' of undefined
err.status: undefined
err.stack: TypeError: Cannot read property 'type' of undefined
    at SessionPool.getSessionGroup_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:716:18)
    at SessionPool.spliceSession_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:868:20)
    at SessionPool.borrowSession_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:426:8)
    at SessionPool.getNextAvailableSession_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:655:8)
    at /Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:943:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

when i do 2 parallel async select

```
const sigOut = (idPath, cb) => {
        let tableName = tableSchema.table;

        let error = (err, errLocation, apiResponse) => dbUtils.getDsError(err, `UserSession.get\\${errLocation}`, idPath, apiResponse);

        let keys = idPath.split('_');

        options.database.run({
            sql: `SELECT * FROM ${tableName} WHERE userId = @userId AND userSessionId = @userSessionId`,
            params: {
                userId: keys[0],
                userSessionId: keys[1]
            },
            type: {
                userId: 'string',
                userSessionId: 'string'
            }
        }, (err, rows) => {
            if (err) {
                return cb(error(err, 'select UserSession...idPath...'));
            }

            return cb(null, rows.length > 0 ? dbUtils.fromSpannerRow(rows[0], options) : undefined);
        });
    };

async.parallel([(cb) => {
        if (!req.params.SessionID) {
            return cb();
        }
        sigOut(req.params.SessionID, cb);

    }, (cb) => {
        if (!req.cookies.SessionID) {
            return cb();
        }
        sigOut(req.cookies.SessionID, cb);
    }
    ], (err) => {
        if (err) {
            return next(err);
        }
        return res.redirect(signInUrl(redirect_uri));
    });
```

can you look this asap.
Thanks

Spanner version is 1.5.0

**Comment by Chipintoza** [comment]
@callmehiphop 

if i change with

` async.waterfall(`

it works.
but same error heppan in many places

**Comment by callmehiphop** [comment]
@Chipintoza I wrote a pretty minimal test trying to reproduce this

```js
      asyncjs.parallel([
        cb => db.run('SELECT 1', cb),
        cb => db.run('SELECT 1', cb),
        cb => db.run('SELECT 1', cb),
        cb => db.run('SELECT 1', cb),
        cb => db.run('SELECT 1', cb),
      ], done);
```

But I'm unable to reproduce doing so. Is there anything special about `options.database`? Is it a custom wrapper, etc.

**Comment by Chipintoza** [comment]
@callmehiphop i add you in my projects
you can look at:  [router.get('/sign-out/:SessionID?', (req, res) => {](https://github.com/GSS-LLC/accounts.gss.ge/blob/e815a6fd195ec3d2157d5375c2c328b5123ecb16/server/routes.js#L618)

it use from another project:
[dbUtils.getSpannerInstance](https://github.com/GSS-LLC/database-utils.gss.ge/blob/b3e72dc81036409ff6a64a967e6d9974a851a131/dbUtils.js#L756)
and
[dbUtils.getSpannerDatabase](https://github.com/GSS-LLC/database-utils.gss.ge/blob/b3e72dc81036409ff6a64a967e6d9974a851a131/dbUtils.js#L760)

**Comment by Chipintoza** [comment]
@callmehiphop 
i forck @gss-llc/spanner - this is same version 1.5.0
just i add additional retiring. becouse  of [issue 189](https://github.com/googleapis/nodejs-spanner/issues/189)

**Comment by Chipintoza** [comment]
@callmehiphop any updates here?

**Comment by Chipintoza** [comment]
this is a full stack:
```
500 - InternalServerError: err.code: undefined
err.message: Cannot read property 'type' of undefined
err.status: undefined
err.stack: TypeError: Cannot read property 'type' of undefined
at SessionPool.getSessionGroup_ (/usr/accounts-gss-ge/node_modules/@gss-llc/spanner/src/session-pool.js:716:18)
at SessionPool.spliceSession_ (/usr/accounts-gss-ge/node_modules/@gss-llc/spanner/src/session-pool.js:868:20)
at SessionPool.borrowSession_ (/usr/accounts-gss-ge/node_modules/@gss-llc/spanner/src/session-pool.js:426:8)
at SessionPool.getNextAvailableSession_ (/usr/accounts-gss-ge/node_modules/@gss-llc/spanner/src/session-pool.js:655:8)
at /usr/accounts-gss-ge/node_modules/@gss-llc/spanner/src/session-pool.js:943:19
at 
at process._tickCallback (internal/process/next_tick.js:188:7)
err location:
User.expireUserSessionsByWebBrowserID\database.runTransaction((err, tx) => {...
data:
"e2adad06-ef37-4dae-89bd-1a3c7f4380ec"
at Function.dbUtils.getDsError (/usr/accounts-gss-ge/node_modules/@gss-llc/database-utils.gss.ge/dbUtils.js:241:16)
at error (/usr/accounts-gss-ge/server/tables/system/users-sessions-table.js:121:64)
at database.runTransaction (/usr/accounts-gss-ge/server/tables/system/users-sessions-table.js:125:27)
at /usr/accounts-gss-ge/node_modules/@gss-llc/spanner/src/database.js:1267:7
at 
at process._tickCallback (internal/process/next_tick.js:188:7)
```
error starting from: database.js:1267:7
in dbUtils i change two methods by:
```

    let _spannerInstance;
    dbUtils.getSpannerInstance = () => {
        if (!_spannerInstance)
            _spannerInstance = spannerInstance.instance(envConfig.spanner.instanceName);
        return _spannerInstance;
    };

    let _spannerDatabases = {};
    dbUtils.getSpannerDatabase = (databaseName) => {
        if (!_spannerDatabases[databaseName])
            _spannerDatabases[databaseName] = dbUtils.getSpannerInstance().database(databaseName);

        return _spannerDatabases[databaseName];
    };
```

But same happens...

**Comment by callmehiphop** [comment]
@Chipintoza thanks for the full trace, its been helpful. However I'm still having some difficulties reproducing the issue. I noticed that you're using a custom install of Spanner, would that be the one found at https://github.com/GSS-LLC/nodejs-spanner?

**Comment by Chipintoza** [comment]
@callmehiphop Yes. it is same as source version 1.5.0. you can look a branch [My Fixes - additional retries](https://github.com/GSS-LLC/nodejs-spanner/commit/fe64363e813ad04cd7d8de60a85d6bf5483128bd) As i mention i just add additional retiring because of [issue 189](https://github.com/googleapis/nodejs-spanner/issues/189)

When I change with [https://github.com/googleapis/nodejs-spanner](https://github.com/googleapis/nodejs-spanner) same exceptions heppen. No matter what i use.
I need urgently to correct this. Today I will try to look at the session-pool and maybe I'll have a little bit of your help.
Thank you

**Comment by Chipintoza** [comment]
@callmehiphop 
i have default sessions_pool options:

```
var DEFAULTS = {
  acquireTimeout: Infinity,
  concurrency: 10,
  fail: false,
  idlesAfter: 10,
  keepAlive: 50,
  max: 100,
  maxIdle: 1,
  min: 0,
  writes: 0,
};

```
i change:
```
SessionPool.prototype.getSession_ = function(type) {
  var self = this;

  var available = this.available();
  var acquires = this.acquireQueue_.size;

var trace = SessionPool.formatTrace_(stackTrace.get());

  if (available && !acquires) {
console.log('this.getNextAvailableSession_(type);')
console.log(trace)
    return this.getNextAvailableSession_(type);
  }

  if (this.options.fail) {
    return Promise.reject(new Error('No resources available.'));
  }

console.log('[this.waitForNextAvailable_(type)]')
console.log(trace)
  var promises = [this.waitForNextAvailable_(type)];
  var shouldCreate =
    !this.isFull() && available + this.pendingCreates_ < acquires + 1;

  if (shouldCreate) {
    var createPromise = new Promise(function(resolve, reject) {
      self.createSession_(type).then(function() {
        self.emit('available');
      }, reject);
    });

    promises.push(createPromise);
  }

  return this.race_(promises);
};
```

log was:

```
DEBUG GET - http://accounts.gss.local:9001/sign-out/1e62b2fd-5170-45a5-a139-bf58389cec46_27b8b61b-0709-46c8-b83e-2531aaddbc57
[this.waitForNextAvailable_(type)]
Session leak detected!
    at SessionPool.getSession (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:235:15)
    at null (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:362:10)
    at emitOne (events.js:116:13)
    at emit (events.js:211:7)
    at obj.(anonymous function) (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/stubs/index.js:28:22)
    at Readable.read (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/readable-stream/lib/_stream_readable.js:443:10)
    at resume_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/readable-stream/lib/_stream_readable.js:790:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at _tickCallback (internal/process/next_tick.js:180:9)
[this.waitForNextAvailable_(type)]
Session leak detected!
    at SessionPool.getSession (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:235:15)
    at null (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:362:10)
    at emitOne (events.js:116:13)
    at emit (events.js:211:7)
    at obj.(anonymous function) (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/stubs/index.js:28:22)
    at Readable.read (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/readable-stream/lib/_stream_readable.js:443:10)
    at resume_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/readable-stream/lib/_stream_readable.js:790:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at _tickCallback (internal/process/next_tick.js:180:9)
this.getNextAvailableSession_(type);
Session leak detected!
    at SessionPool.getWriteSession (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:244:15)
    at Database.getTransaction (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/database.js:803:10)
    at wrapper (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@google-cloud/common/src/util.js:749:29)
    at Database.runTransaction (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/database.js:1265:8)
    at UserSession.expireUserSessionsByWebBrowserID (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/server/tables/system/users-sessions-table.js:123:18)
    at _usersSessionsTable.get (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/server/routes.js:644:33)
    at options.database.run (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/server/tables/system/users-sessions-table.js:79:20)
    at null (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/database.js:990:7)
    at emitNone (events.js:111:20)
    at emit (events.js:208:7)
    at endReadableNT (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at _tickCallback (internal/process/next_tick.js:180:9)
this.reads_ - length & [0]
1
Session {
  request: [Function: bound wrapper],
  lastUsed: 1533400876760,
  formattedName_: 'projects/spanner-gss-ge-196012/instances/gss-data/databases/accounts-gss-ge-dev-test/sessions/AB0Y85BRsTKuPOVcK8Z-hRJJqg3X85UWPsPa3QUdp74mxC6vlw_8FXP9GfA',
  delete: [Function],
  getMetadata: [Function],
  keepAlive: { [Function: wrapper] promisified_: true },
  transaction: [Function],
  setMetadata: { [Function: wrapper] promisified_: true },
  requestStream: [Function],
  requestWritableStream: [Function],
  create: { [Function: wrapper] promisified_: true },
  exists: { [Function: wrapper] promisified_: true },
  get: { [Function: wrapper] promisified_: true },
  request_: [Function],
  type: 'readonly' }
this.reads_ - length & [0]
0
undefined

req.url - http://accounts.gss.local:9001/sign-out/1e62b2fd-5170-45a5-a139-bf58389cec46_27b8b61b-0709-46c8-b83e-2531aaddbc57
InternalServerError: err.code: undefined
err.message: Cannot read property 'type' of undefined
err.status: undefined
err.stack: TypeError: Cannot read property 'type' of undefined
    at SessionPool.getSessionGroup_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:726:18)
    at SessionPool.spliceSession_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:878:20)
    at SessionPool.borrowSession_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:426:8)
    at SessionPool.getNextAvailableSession_ (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:659:8)
    at /Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/spanner/src/session-pool.js:953:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
err location:
UserSession.get\select UserSession...idPath...
data:
"1e62b2fd-5170-45a5-a139-bf58389cec46_c9277796-cebd-4002-975e-6020f9ab0ae4"
    at Function.dbUtils.getDsError (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/dbUtils.js:241:16)
    at error (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/server/tables/system/users-sessions-table.js:60:64)
    at DestroyableTransform.options.database.run (/Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/server/tables/system/users-sessions-table.js:76:27)
    at emitOne (events.js:121:20)
    at DestroyableTransform.emit (events.js:211:7)
    at /Users/Chipintoza/GSS Projects/gss.ge/accounts.gss.ge/node_modules/through2/through2.js:19:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I have no time to understand session pool full.
Hope all this information helps you, and you can fix this issue.

Thank you.

**Comment by Chipintoza** [comment]
@callmehiphop @vkedia  - any updates here? can you reopen this issue?

**Comment by callmehiphop** [comment]
@Chipintoza I still haven't been able to reproduce, but I have a PR open for some related that might help resolve it. If you could test #243 that would be awesome!

**Comment by Chipintoza** [comment]
@callmehiphop i test and it works!
