### ISSUE TITLE
Error: Value of type undefined not recognized

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#195]
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.4
  - npm version: v6.0.0
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce
(not sure if this will reproduce it but this is what causes it for me)
  1.  Setup database with interleaved tables
  2. Run a select to get 50 interleaved records (from multiple different parent tables)
  3. Attempt to delete these cross-parent records using a `deleteRows` call within a `runTransaction` block (causes error)

The full error stack is as follows:
```
Error: Value of type undefined not recognized.
    at ObjectToStructConverter.encodeValue_ (/opt/app/node_modules/@google-cloud/spanner/node_modules/@google-cloud/common-grpc/src/service.js:953:13)
    at Function.GrpcService.encodeValue_ (/opt/app/node_modules/@google-cloud/spanner/node_modules/@google-cloud/common-grpc/src/service.js:528:52)
    at encode (/opt/app/node_modules/@google-cloud/spanner/src/codec.js:224:29)
    at Array.map (<anonymous>:null:null)
    at /opt/app/node_modules/@google-cloud/spanner/src/transaction-request.js:351:31
    at Array.map (<anonymous>:null:null)
    at TransactionRequest.deleteRows (/opt/app/node_modules/@google-cloud/spanner/src/transaction-request.js:349:26)
    at spannerStoresDb.runTransaction (/opt/app/index.js:25:13)
    at /opt/app/node_modules/@google-cloud/spanner/src/database.js:1279:5
    at /opt/app/node_modules/@google-cloud/spanner/src/database.js:804:7
    at <anonymous>:null:null
```

Another engineer on my team said he has seen this error when doing querying large amounts of data as well if that helps.

Found this while looking around which makes me think calling this function should not throw an error.  

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2008#issuecomment-280864896

Let me know if my assumption there is wrong and I should be wrapping this code with better error handling

**Comment by walshie4** [comment]
🤦‍♂️ just realized I fell into the same trap as mentioned in the previous ticket, destructured using the wrong name and got `undefined`
