### ISSUE TITLE
runStream returning incomplete and out of bounds for non existing values

### ISSUE THREAD

**Issue by saranyasengo** [googleapis/nodejs-spanner#1959]
#### Environment details

  - OS: Google Container OS
  - Node.js version: 18.15
  - npm version: 9.5.0
  - `@google-cloud/spanner` version: 5.18.0

#### Steps to reproduce

This error is inconsistently happening its similar to issues https://github.com/googleapis/nodejs-spanner/issues/197 and https://github.com/googleapis/nodejs-spanner/issues/180

The code which gives error
`const rowsStream = spannerDb.runStream({
      sql: `SELECT * FROM ${TABLE_NAME} ORDER BY storeId, started DESC`,
      json: true,
    });
`

Error thrown as below

`GoogleError: Serializing column "started" encountered an error: Integer 211959131678161148 is out of bounds. Call row.toJSON({ wrapNumbers: true }) to receive a custom type.
    at Int.valueOf (/opt/app/node_modules/@google-cloud/spanner/build/src/codec.js:121:19)
    at convertValueToJson (/opt/app/node_modules/@google-cloud/spanner/build/src/codec.js:263:22)
    at Object.convertFieldsToJson (/opt/app/node_modules/@google-cloud/spanner/build/src/codec.js:239:31)
    at Array.value (/opt/app/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:206:38)
    at PartialResultStream._addValue (/opt/app/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:187:34)
    at /opt/app/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:163:24
    at Array.forEach (<anonymous>)
    at PartialResultStream._addChunk (/opt/app/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:162:16)
    at PartialResultStream._transform (/opt/app/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:85:24)
    at Transform._write (node:internal/streams/transform:175:8)
    at obj.<computed> [as _write] (/opt/app/node_modules/stubs/index.js:26:26)
    at doWrite (node:internal/streams/writable:411:12)
    at clearBuffer (node:internal/streams/writable:572:7)
    at onwrite (node:internal/streams/writable:464:7)
    at node:internal/streams/transform:190:7
    at PartialResultStream._tryResume (/opt/app/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:108:13)`
    
    started column in table doesn't has the value '211959131678161148' thrown. The storeId column has this value. Looks like it swapped or wrongly mapping the values for columns. 
    
    This error not thrown always and not reproducible in local as well.

Thanks!

**Comment by saranyasengo** [comment]
@surbhigarg92 Can we get any update on this. spanner runStream causing the issues with swapping the column values

**Comment by surbhigarg92** [comment]
Hi @saranyasengo Sorry for the delay. I haven't been able to look into this issue. Can you please share the below information to help me reproduce this issue ? 

1. Did you start seeing this issue recently or was it always there ? 
2. Can you share the schema of your table ?
3. What is the size of the table ?
4. Can you try upgrading to the latest version of library and see if you are able to reproduce this issue ?

**Comment by saranyasengo** [comment]
Hey @surbhigarg92  

I believe the issue is from so long, but we captured recently since its thrown out of bounds error. But the actual issue is column values are swapped.

We have upgraded recently to @google-cloud/spanner version 7.0.0 still we see the values are getting swapped. 

Schema of the table is secure to share. We have created google support ticket for this. I will share the table schema, sample data's with table and how the spanner runStream returns the data in support ticket.

**Comment by surbhigarg92** [comment]
@saranyasengo Can you please try using the latest release https://github.com/googleapis/nodejs-spanner/releases/tag/v7.4.0 and let us know if this resolves your issue ?

**Comment by saranyasengo** [comment]
@surbhigarg92 I will update to latest version and since its not reproducible in local and its coming weekly once. I will update and monitor for couple of weeks and update on this. 

Can you please share us the reproduction step to confirm before using the latest one?

**Comment by surbhigarg92** [comment]
We found that error was happening in a particular case where the pending value were getting cleared when partialResultSet had a resume token . Please refer https://github.com/googleapis/nodejs-spanner/pull/2000 for the fix and test cases added.

**Comment by saranyasengo** [comment]
@surbhigarg92  I have upgraded the version to 7.4.0 and now I see this issue is not coming for past 2 days, But we are facing different type of issue now, hence rollback the changes to previous one.

The specific error we are getting is `Error: 3 INVALID_ARGUMENT: The code field is required for types.` and I will attach the table schema and query details in the google support ticket. Please help us on fixing this.

**Comment by surbhigarg92** [comment]
@saranyasengo The error looks like because of a recent feature which was launched https://github.com/googleapis/nodejs-spanner/pull/1869 

I am working on fixing this. Sorry for the inconvenience.

**Comment by surbhigarg92** [comment]
@saranyasengo As communicated earlier the error was happening because of a recent feature launch. We have reverted that feature for the time being. 

Can you please try using [7.5.0](https://github.com/googleapis/nodejs-spanner/releases/tag/v7.5.0) release

**Comment by saranyasengo** [comment]
@surbhigarg92 We will use 7.5.0 and will monitor for somedays for fixes.

**Comment by surbhigarg92** [comment]
@saranyasengo Let us know if this worked for you

**Comment by saranyasengo** [comment]
@surbhigarg92  it works, So far we have not faced this issue.

**Comment by surbhigarg92** [comment]
@saranyasengo We are closing this ticket. Please feel free to reopen if you face any issues.
