### ISSUE TITLE
Cannot read property `type` of undefined

### ISSUE THREAD

**Issue by axot** [googleapis/nodejs-spanner#305]
We recently got an error shows bellow,

```
2018/08/23 10:49:36:753][WORKER: 28885 6]<debug>Llibs.errorResponse) Error Trace: TypeError: Bad Request
at SessionPool.getSessionGroup_ (@google-cloud/spanner/src/session-pool.js:709:18)
at SessionPool.spliceSession_ (@google-cloud/spanner/src/session-pool.js:861:20)
at SessionPool.borrowSession_ (@google-cloud/spanner/src/session-pool.js:419:8)
at SessionPool.getNextAvailableSession_ (@google-cloud/spanner/src/session-pool.js:648:8)
at @google-cloud/spanner/src/session-pool.js:936:19 at <anonymous
```

`session-pool.js`
```
623 /**
624  * Grabs the next available session.
625  *
626  * @private
627  *
628  * @param {string} type The desired session type.
629  * @returns {Promise<Session>}
630  */
631 SessionPool.prototype.getNextAvailableSession_ = function(type) {
632   var self = this;
633   var session = null;
634
635   if (type === READONLY && this.reads_.length) {
636     session = this.reads_[0];
637   } else if (this.writes_.length) {
638     session = this.writes_[0];
639   }
640
641   if (session) {
642     self.borrowSession_(session);
643     return Promise.resolve(session);
644   }
645
646   // if session is not defined then create a ReadWrite session
647   session = this.reads_[0];
648   self.borrowSession_(session);
649
650   return this.race_(self.createTransaction_(session))
651     .then(function() {
652       return session;
653     })
654     .catch(function(err) {
655       self.release_(session);
656       throw err;
657     });
658 };
```

At line 647, does this error happens when the length of this.reads_ is zero, I found current master branch's `session-pool.js` was refactored, we are using 1.4.x now. Hope this could be fixed soon.

Thank you.

**Comment by stephenplusplus** [comment]
@callmehiphop was this fixed?

**Comment by callmehiphop** [comment]
@axot we have since released a new version including a refactored session pool implementation. If you upgrade to 2.0.0 I believe this issue will go away.
