### ISSUE TITLE
select with empty array parameters

### ISSUE THREAD

**Issue by Chipintoza** [googleapis/nodejs-spanner#42]
OS: Mac OSX 10.13.1
Node.js version: 8.9.1
npm version: 5.5.1
version: 0.8.0

simple query:

```
tx.run({
                    sql: `SELECT * FROM Goods WHERE goodId in UNNEST(@goodIds)`,
                    params: {
                        goodIds: [],
                    }
}
```
return error:

```
req.url - http://retail.gss.local:9002/api/goods-documents/upsert
InternalServerError: err.code: 3
err.message: The code field is required for types.
err.status: undefined
err.stack: Error: The code field is required for types.
    at ClientReadableStream._emitStatusIfDone (/Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/grpc/src/node/src/client.js:209:19)
    at ClientReadableStream._receiveStatus (/Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/grpc/src/node/src/client.js:188:8)
    at /Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/grpc/src/node/src/client.js:600:14
err location:
GoodsDocument.upsert\select...GoodsDocuments...rollback...
data:
{"document":{"organizationId":999,"documentId":1,"date":1511357040129,"number":"1","transactionType":1,"subject":"სატესტო საბუთი","stockId":1,"receivedStockId":2,"accomplished":true,"timestamp":1511357072148,"shardId":3},"transactions":[]}
apiResponse:
{}
    at Function.dbUtils.getDsError (/Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/dbUtils.js:218:16)
    at error (/Users/Chipintoza/GSS Projects/retail.gss.ge/server/tables/goods-documents-table.js:273:64)
    at tx.rollback (/Users/Chipintoza/GSS Projects/retail.gss.ge/server/tables/goods-documents-table.js:306:32)
    at /Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:456:5
    at /Users/Chipintoza/GSS Projects/retail.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:329:7
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Chipintoza** [comment]
this select works:

 ```
               tx.run({
                    sql: `SELECT * FROM Goods WHERE goodId in UNNEST(@goodIds)`,
                    params: {
                        goodIds: [],
                    },
                    types: {
                        goodIds: {
                            type: 'array',
                            child: 'int64'
                        }
                    }, cb);

```

**Comment by stephenplusplus** [comment]
Thanks for reporting. Should that query execute without error? Or should we improve the error?

**Comment by stephenplusplus** [comment]
Sorry, didn't see your follow-up comment.

@callmehiphop for thoughts on how to handle.

**Comment by callmehiphop** [comment]
@Chipintoza It is not always possible for Spanner to infer the right SQL type from JSON, especially for empty values. You can configure the `types` property to work around this.

```js
tx.run({
  sql: `SELECT * FROM Goods WHERE goodId in UNNEST(@goodIds)`,
  params: {
    goodIds: []
  },
  types: {
    goodIds: {
      type: 'array',
      child: 'string'
    }
  }
}, (err, rows) => {});
```

**Comment by Chipintoza** [comment]
there is also some errors:
in transaction.js
[var child;](https://github.com/googleapis/nodejs-spanner/blob/ca0f55b0ccb595519b18ab6ed4b6920aeccdd05a/src/transaction.js#L725)

it must be initialised:
`var child = undefined;`

if in params first property is array all rest properties becomes array 

same is in database.js
```
var childType;
var child;

```
this two files has difference logic an is this right?

because of this in I'm forced define types :(

**Comment by Chipintoza** [comment]
@stephenplusplus thank you 
please see last my comment.

**Comment by Chipintoza** [comment]
@stephenplusplus  It would be good if it was documented [in docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/0.5.0/spanner/transaction?method=run)

**Comment by Chipintoza** [comment]
@callmehiphop that means every time when i have array type parameter i need to configure the types property. is this good? if it is, it must be documented.

**Comment by callmehiphop** [comment]
I hadn't noticed the bug you found, I'll try and resolve this right now.
