### ISSUE TITLE
Request had invalid authentication credentials error when calling Spanner

### ISSUE THREAD

**Issue by alexliffick** [googleapis/nodejs-spanner#482]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 6.14.4
  - npm version: 6.4.1
  - `@google-cloud/spanner` version: 2.2.1

#### Steps to reproduce
We have a table called "users" where my username exists with a uuid-based `recordId` as the primary key. Use the following code with a valid auth.json file:
```javascript
'use strict';
const {Spanner} = require('@google-cloud/spanner');
var spanner = new Spanner({
	projectId: '<enter_project_id>',
	keyFilename: './auth.json'
});

var instance = spanner.instance(<enter_spanner_instance>);
let databaseName = '<enter_db_name>';
const database = instance.database(databaseName);
const table = database.table('users');

const query1 = {
	sql: 'SELECT recordId FROM users where username = \'aliffick\'',
};

database
.run(query1)
.then(results => {
	const rows = results[0];
	rows.forEach(row => {
		const json = row.toJSON();
		console.log(json.recordId);
	});
  })
  .catch(err => {
    console.error('ERROR in select:', err);
  });
```
First script output before npm update:
```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ nodejs spannerTest.js 
3e3b5f3f-dd59-4164-8fcf-92fa04ef1fee
```
Npm list output before npm update:
```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ npm list | grep google
└─┬ @google-cloud/spanner@1.4.0
  ├─┬ @google-cloud/common@0.17.0
  │ ├── google-auto-auth@0.10.0 deduped
  ├─┬ @google-cloud/common-grpc@0.6.1
  │ ├── @google-cloud/common@0.17.0 deduped
  ├─┬ google-auto-auth@0.10.0
  │ ├─┬ google-auth-library@1.4.0
  │ │ │ ├─┬ google-p12-pem@1.0.2
  ├─┬ google-gax@0.16.1
  │ ├── google-auto-auth@0.10.0 deduped
  │ ├── google-proto-files@0.15.1 deduped
  ├─┬ google-proto-files@0.15.1
```
Script output after npm update:
```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ nodejs spannerTest.js 
ERROR in select: { Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at Object.exports.createStatusError (/home/aliffick/citizendev/tmp/spanner/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/home/aliffick/citizendev/tmp/spanner/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/home/aliffick/citizendev/tmp/spanner/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/home/aliffick/citizendev/tmp/spanner/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/home/aliffick/citizendev/tmp/spanner/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 16,
  metadata: Metadata { _internal_repr: { 'grpc-server-stats-bin': [Object] } },
  details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
  note: 'Exception occurred in retry method that was not classified as transient' }
```
Npm list output after npm update:
```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ npm list | grep google
└─┬ @google-cloud/spanner@2.2.1
  ├─┬ @google-cloud/common-grpc@0.9.2
  │ ├─┬ @google-cloud/common@0.26.2
  │ │ ├── @google-cloud/projectify@0.3.2 deduped
  │ │ ├── @google-cloud/promisify@0.3.1 deduped
  │ │ ├── google-auth-library@2.0.1 deduped
  │ ├── @google-cloud/projectify@0.3.2 deduped
  │ ├── @google-cloud/promisify@0.3.1 deduped
  ├─┬ @google-cloud/paginator@0.1.2
  ├── @google-cloud/projectify@0.3.2
  ├── @google-cloud/promisify@0.3.1
  ├─┬ google-auth-library@2.0.1
  │ │ ├─┬ google-p12-pem@1.0.3
  ├─┬ google-gax@0.22.1
  │ ├── google-auth-library@2.0.1 deduped
  │ ├─┬ google-proto-files@0.18.0
```

**Comment by JustinBeckwith** [comment]
Greetings!  Can you run this for me and share the output?

`npm ls gtoken`

Also - could you try deleting your `package-lock.json` and `node_modules` folders, running `npm install`, and seeing if that solves the issue?

**Comment by alexliffick** [comment]
I wondered about gtoken and further down in the google-p12-pem package but have no way to prove that v1.0.3 of that is causing the issue. Our services that are still working have 1.0.2.

```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ npm ls gtoken
spanner-cleanup@1.0.0 /home/aliffick/citizendev/tmp/spanner
└─┬ @google-cloud/spanner@2.2.1
  └─┬ google-auth-library@2.0.1
    └── gtoken@2.3.1 
```

**Comment by JustinBeckwith** [comment]
That's the problem.  We have the `latest` tag on `2.3.0` of gtoken right now because of a bad patch release of `2.3.1`.  If you delete your `package-lock.json` and `node_modules`, and run `npm install` - does it install `2.3.0` for you?

**Comment by alexliffick** [comment]
@JustinBeckwith Thanks for that info, it helps knowing that it definitely is downstream. Sorry I missed that in your first comment, but I've done it a few times and still get 2.3.1:
```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ rm -rf package-lock.json 
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ rm -rf node_modules/
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ npm install

> grpc@1.16.1 install /home/aliffick/citizendev/tmp/spanner/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[grpc] Success: "/home/aliffick/citizendev/tmp/spanner/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node" is installed via remote

> protobufjs@6.8.8 postinstall /home/aliffick/citizendev/tmp/spanner/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN spanner-cleanup@1.0.0 No repository field.

added 195 packages from 160 contributors in 9.075s
aliffick@Alex-Laptop:~/citizendev/tmp/spanner$ npm ls gtoken
spanner-cleanup@1.0.0 /home/aliffick/citizendev/tmp/spanner
└─┬ @google-cloud/spanner@2.2.1
  └─┬ google-auth-library@2.0.1
    └── gtoken@2.3.1 
```

**Comment by alexliffick** [comment]
If it helps, google-auth-library in the installed spanner module package.json is ^2.0.0 and gets 2.0.1, which in turn has ^2.3.0 in it's package.json according to their github page.
```shell
aliffick@Alex-Laptop:~/citizendev/tmp/spanner/node_modules$ npm ls google-auth-library
spanner-cleanup@1.0.0 /home/aliffick/citizendev/tmp/spanner
└─┬ @google-cloud/spanner@2.2.1
  ├─┬ @google-cloud/common-grpc@0.9.2
  │ └─┬ @google-cloud/common@0.26.2
  │   └── google-auth-library@2.0.1  deduped
  ├── google-auth-library@2.0.1 
  └─┬ google-gax@0.22.1
    └── google-auth-library@2.0.1  deduped
```
