### ISSUE TITLE
pack and install test fails

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-spanner#635]
See https://github.com/googleapis/nodejs-spanner/pull/634

**Comment by stephenplusplus** [comment]
Did you start seeing this with #634? Is the error always:

```
 1) 📦 pack and install
       should be able to use the d.ts:
     Error: Command failed: npm install --unsafe-perm
      at Promise.all.then.arr (node_modules/execa/index.js:231:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Earlier in the build, there's also:

```
> tsc -p .
node_modules/p-queue/index.d.ts:81:54 - error TS2344: Type 'DefaultAddOptions' does not satisfy the constraint 'QueueAddOptions'.
  Index signature is missing in type 'DefaultAddOptions'.
81  EnqueueOptionsType extends PQueue.QueueAddOptions = PQueue.DefaultAddOptions
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by callmehiphop** [comment]
Looks like there's an open issue for this already https://github.com/sindresorhus/p-queue/issues/66
