### ISSUE TITLE
Cannot call `transaction.run` sequentially before commit

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-spanner#657]
While looking into an unrelated issue I stumbled upon something that seems odd.

Trying to call transaction.run, transaction.run results in an error. It would seem to me, at surface level, that this should be possible for users to do.

### Error
```
(node:59639) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Previously received a different request with this seqno. seqno=0
    at Object.exports.createStatusError (/Users/crwilcox/repro/node_modules/grpc/src/common.js:91:15)
    at ClientReadableStream._emitStatusIfDone (/Users/crwilcox/repro/node_modules/grpc/src/client.js:233:26)
    at ClientReadableStream._receiveStatus (/Users/crwilcox/repro/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/crwilcox/repro/node_modules/grpc/src/client_interceptors.js:1272:15)
    at InterceptingListener._callNext (/Users/crwilcox/repro/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/crwilcox/repro/node_modules/grpc/src/client_interceptors.js:618:8)
    at Object.onReceiveStatus (/Users/crwilcox/repro/node_modules/grpc-gcp/build/src/index.js:93:25)
    at InterceptingListener._callNext (/Users/crwilcox/repro/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/crwilcox/repro/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/crwilcox/repro/node_modules/grpc/src/client_interceptors.js:1029:24
```

### Full Sample
```
const {Spanner} = require('@google-cloud/spanner');

const spanner = new Spanner();

const instance = spanner.instance('testinstance');
const db = instance.database('people');

async function insert() {
    const query = 'INSERT INTO my_table (id, name, petName, hobby) VALUES (@id, @name, @petName, @hobby)';
    await db.runTransactionAsync(async (transaction) => {
        await transaction.run({
            sql: query,
            params: {
                id: 47,
                name: 'chris',
                petName: 'ace',
                hobby: 'acrobatics'
            }
        });
        await transaction.run({
            sql: query,
            params: {
                id: 47,
                name: 'chris',
                petName: 'buddy',
                hobby: 'baton'
            }
        });
        await transaction.commit().catch(r=>console.log(r));
    });
};

insert()
```

**Comment by callmehiphop** [comment]
So we chatted about this offline, but the issue is that `runUpdate()` should be called for DML statements. My guess is that in this case the backend end infers a seqno of 0 if its missing from the request and throws this error. 

We could throw an error if the seqno is missing from a DML statement, but that feels dirty to me.

**Comment by crwilcox** [comment]
It seems odd that run won't allow inserting multiple rows, but `runUpdate` would. 

In what situations, as a user, would I prefer `run` to `runUpdate`?

**Comment by callmehiphop** [comment]
@crwilcox I think the general rule of thumb would be to use `run` for reading and `runUpdate` for inserts/updates. Although technically `run` would work there too, I think the user would just have to supply their own `seqno`.
