### ISSUE TITLE
spanner: client throws error when introducing params: field to request

### ISSUE THREAD

**Issue by skuruppu** [googleapis/nodejs-spanner#845]
#### Environment details

  - OS: unknown
  - Node.js version: unknown
  - npm version: unknown
  - `@google-cloud/spanner` version: unknown

#### Steps to reproduce

Customer was interested in getting query execution plan using [Node.js client library for Spanner](https://googleapis.dev/nodejs/spanner/latest/index.html).

The following code works:
```ts
const spanner = require('@google-cloud/spanner');

const client = new spanner.v1.SpannerClient({
  projectID: '[PROJECT-NAME]',
});

var sessionName = '';
var projectName = '[PROJECT-NAME]';
var instanceName = '[INSTANCE-NAME]';
var databaseName = '[DATABASE-NAME]'; 

const formattedDatabase = client.databasePath(projectName, instanceName, databaseName);

client.createSession({database: formattedDatabase})
  .then(responses => {
    const response = responses[0];
    var pathlist = response.name.split('/');
    sessionName = pathlist[7];
    const formattedSession = client.sessionPath(projectName, instanceName, databaseName, sessionName);

    //Create SQL Query and Issue the request with queryMode set to 0 to get only the statement restult, 1 to get the statement result + query plan 2 to get the statement result + query plan + stats
    const sql = 'SELECT tracking_id FROM trackings WHERE tracking_id = 1';
    const request = {
      session: formattedSession,
      sql: sql,
      queryMode: 2,
    };

    client.executeSql(request)
      .then(responses => {
        const response = responses[0];
        console.log(response.stats.queryPlan)
      });

      .catch(err => {
        console.error(err);
      });

      //Delete the session
      const formattedName = client.sessionPath(projectName, instanceName, databaseName, sessionName);
      client.deleteSession({name: formattedName}).catch(err => {
        console.error(err);
      });
  })

  .catch(err => {
    console.error(err);
  })
```

But it fails when a params: field is introduced on the request section that serves as input to the [executeSQL](https://googleapis.dev/nodejs/spanner/latest/v1.SpannerClient.html#executeSql) method:

```ts
...
    const request = {
       session: formattedSession,
       sql: `SELECT tracking_id FROM trackings WHERE tracking_id=@tracking_id`,
       params: {
          tracking_id: '1'
       },
       queryMode: 2,
     };

const [response] = await client.executeSql(request)
...
```

When introducing this field, the code will fail to return any response and results in the following error message:
```ts
{ Error: 3 INVALID_ARGUMENT: No parameter found for binding: tracking_id

at Object.callErrorFromStatus (/home/[XXXX]/nodejs-spanner/samples/node_modules/@grpc/grpc-js/build/src/call.js:30:26)

at Http2CallStream.call.on (/home/[XXXXX]/nodejs-spanner/samples/node_modules/@grpc/grpc-js/build/src/client.js:96:33)

at Http2CallStream.emit (events.js:187:15)

at process.nextTick (/home/[XXXXX]/nodejs-spanner/samples/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)

at process._tickCallback (internal/process/next_tick.js:61:11)

code: 3,
details: 'No parameter found for binding: tracking_id',
metadata:
Metadata {
internalRepr: Map { 'grpc-server-stats-bin' => [Array] },
options: {} },
note:
'Exception occurred in retry method that was not classified as transient' }
```

**Comment by skuruppu** [comment]
@AVaksman if your team can take a look at this issue that would be great.

**Comment by AVaksman** [comment]
@laljikanjareeya could you please investigate.

**Comment by olavloite** [comment]
This is not a problem in the client library. The example is using the generated gapic client instead of the hand-written Spanner client library. The gapic client is intended for advanced users and for writing client libraries etc.

The reason for the error in this case is that the user must take care to specify the parameters including all type information in the correct way. That is a lot more work when you use the gapic client instead of the client library. A working example for using the gapic client for this would be this:

```typescript
      const formattedDatabase = client.databasePath(
        projectName,
        instanceName,
        databaseName
      );

      client
        .createSession({database: formattedDatabase})
        .then(responses => {
          const response = responses[0];
          const pathlist = response.name.split('/');
          sessionName = pathlist[7];
          const formattedSession = client.sessionPath(
            projectName,
            instanceName,
            databaseName,
            sessionName
          );

          //Create SQL Query and Issue the request with queryMode set to 0 to get only the statement result, 1 to get the statement result + query plan 2 to get the statement result + query plan + stats
          const sql = 'SELECT * FROM Albums WHERE AlbumTitle LIKE @title';
          const request = {
            session: formattedSession,
            sql,
            params: {
              fields: {
                title: {stringValue: 'Go%'},
              },
            },
            paramTypes: {
              title: {code: 'STRING'},
            },
            queryMode: 2,
          };

          client
            .executeSql(request)
            .then(responses => {
              const response = responses[0];
              console.log(response.stats!.queryPlan);
            })
            .catch(err => {
              console.error(err);
            });

          //Delete the session
          const formattedName = client.sessionPath(
            projectName,
            instanceName,
            databaseName,
            sessionName
          );
          client.deleteSession({name: formattedName}).catch(err => {
            console.error(err);
          });
        })
        .catch(err => {
          console.error(err);
        });
```

**Comment by skuruppu** [comment]
The customer has been forwarded the reply from @olavloite so closing this issue.
