### ISSUE TITLE
bug: row.toJSON can cause 'Out of bounds' error

### ISSUE THREAD

**Issue by olavloite** [googleapis/nodejs-spanner#935]
Calling `JSON.stringify(row)` on a row with an INT64 column can cause the error below.

```
/home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/codec.js:196
            throw e;
            ^

Error: Serializing column "ColInt64Array" encountered an error: Integer 7920930067379896181 is out of bounds. Call row.toJSON({ wrapNumbers: true }) to receive a custom type.
    at Int.valueOf (/home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/codec.js:115:19)
    at convertValueToJson (/home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/codec.js:212:22)
    at /home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/codec.js:224:35
    at Array.map (<anonymous>)
    at convertValueToJson (/home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/codec.js:224:22)
    at Object.convertFieldsToJson (/home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/codec.js:189:26)
    at Array.value (/home/loite/WebstormProjects/nodejs-spanner-knut/samples/node_modules/@google-cloud/spanner/build/src/partial-result-stream.js:143:38)
    at JSON.stringify (<anonymous>)
    at DestroyableTransform.<anonymous> (/home/loite/WebstormProjects/nodejs-spanner-knut/samples/memusage.js:49:42)
```

**Comment by olavloite** [comment]
Known issue, the solution/workaround is given in the error message itself.
